using SpaceBattle.Lib.Lab2;
using SpaceBattle.Lib.Lab5;

namespace SpaceBattle.Tests.Lab5;


public interface ITestMovingObject
{
    Vector Location { get; set; }

    [Adapter(typeof(ITestMovingObject), "Velocity", "Стратегия.НестандартнаяСкорость")]
    Vector Velocity { get; }
}

public class AdapterTests
{
    [Fact]
    public void IoC_ResolveMoveCommand_WithAutoGeneratedAdapter_Success()
    {
        // Arrange
        var objData = new Dictionary<string, object>
        {
            { "Location", new Vector(10, 20) }
            // "Velocity" умышленно не кладем в словарь, так как для него сработает кастомная стратегия атрибута
        };

        // 2. регистрируем в IoC кастомную стратегию для свойства Velocity указанную в атрибуте
        var fixedVelocity = new Vector(5, 5);
        IoC.Resolve<object>("IoC.Register", "Стратегия.НестандартнаяСкорость", (Func<object[], object>)(args => fixedVelocity));

        // 3. регистрируем в IoC автоматическое разрешение команды "Команды.Move"
        // она принимает IDictionary генерирует адаптер на лету и собирает MoveCommand
        IoC.Resolve<object>("IoC.Register", "Команды.Move", (Func<object[], object>)(args =>
        {
            var dict = (IDictionary<string, object>)args[0];
            // енерируем адаптер интерфейса ITestMovingObject для словаря
            var adapter = AdapterGenerator.CreateAdapter<ITestMovingObject>(dict);
            
            // возвращаем MoveCommand обернутый в ICommand (для теста сымитируем через Mock или просто проверим адаптер)
            return adapter;
        }));

        // Act
        var generatedAdapter = IoC.Resolve<ITestMovingObject>("Команды.Move", objData);

        // Assert
        Assert.Equal(new Vector(10, 20), generatedAdapter.Location);
        
        generatedAdapter.Location = new Vector(100, 200);
        Assert.Equal(new Vector(100, 200), objData["Location"]);

        // проверяем что для Velocity отработал атрибут [Adapter] и вызвал стратегию из IoC
        Assert.Equal(fixedVelocity, generatedAdapter.Velocity);
    }
}